// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWVvqF8vlT2xylTC5nHKJ-cBMNfwSiI_o',
    appId: '1:883655907284:web:a8a61d5cc6f7647ec62841',
    messagingSenderId: '883655907284',
    projectId: 'pokemonshop-97cde',
    authDomain: 'pokemonshop-97cde.firebaseapp.com',
    storageBucket: 'pokemonshop-97cde.firebasestorage.app',
    measurementId: 'G-44BMGQ2FKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJWJvLHvXkEVoEX7J0Q1WoZlMJjmEI5tM',
    appId: '1:883655907284:android:1c677cef46a3fd0ec62841',
    messagingSenderId: '883655907284',
    projectId: 'pokemonshop-97cde',
    storageBucket: 'pokemonshop-97cde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP66_1DifuiCAD_ZqkelvL-lCJ9WT2oyU',
    appId: '1:883655907284:ios:3012b5b92144646dc62841',
    messagingSenderId: '883655907284',
    projectId: 'pokemonshop-97cde',
    storageBucket: 'pokemonshop-97cde.firebasestorage.app',
    iosBundleId: 'com.example.flutterproje1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP66_1DifuiCAD_ZqkelvL-lCJ9WT2oyU',
    appId: '1:883655907284:ios:3012b5b92144646dc62841',
    messagingSenderId: '883655907284',
    projectId: 'pokemonshop-97cde',
    storageBucket: 'pokemonshop-97cde.firebasestorage.app',
    iosBundleId: 'com.example.flutterproje1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWVvqF8vlT2xylTC5nHKJ-cBMNfwSiI_o',
    appId: '1:883655907284:web:2ef662c8af0d1d1cc62841',
    messagingSenderId: '883655907284',
    projectId: 'pokemonshop-97cde',
    authDomain: 'pokemonshop-97cde.firebaseapp.com',
    storageBucket: 'pokemonshop-97cde.firebasestorage.app',
    measurementId: 'G-9BYYYZX2XB',
  );
}
